---
title: "Academic application"
author: "Poddaturi, Dinesh R"
date: '2022-04-28'
output: pdf_document
---

Research Project's Name:
People and Economy

In English, describe your research project.

The aim of this project is to understand how the economy evolves by the people's sentiments and expectations. In particular, I posit that the people are the economy, they are the economic systems, and their decisions, sentiments, and expectations change the economy.

In English, describe how Twitter data and/or Twitter APIs will be used in your research project.

I would like to work with Twitter data in the following manner: I gather the overall sentiments of the people in general. For instance good, bad, high, low, war, etc. I couple these with economic terms like inflation, prices, and expectations. Analysis of people's sentiments and the economy will give insights into the economic system itself.


In English, describe your methodology for analyzing Twitter data, Tweets, and/or Twitter users.

Depending on the data items, I will use the common terms people use to express their opinions under hash tags. Once I get aggregate data under those mentioned hash tags, I will gather people's sentiments in those tweets and analyze them.


In English, describe how you will share the outcomes of your research (include tools, data, and/or resources).

This is an open-source project. Once I finish the analysis, I will make the methods, tools used, and the results public. I will not disclose any data that contains private information. As said above, I will only gather people's sentiments and the economic terms.












